# https://www.appveyor.com/docs/appveyor-yml/

# https://www.appveyor.com/docs/macos-images-software/
image: macos

install:
# `brew install ninja` is simpler but takes a lot longer
- curl -L 'https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-mac.zip' -o /tmp/ninja-mac.zip
- unzip /tmp/ninja-mac.zip -d /usr/local/bin/
- which ninja

build_script:
- df -h .
- git clone https://github.com/llvm/llvm-project.git
- git -C llvm-project checkout 1d42ba254fa3203f1ad5916ed414a84312f5bba9
# save 1.5 GB?
# - rm -rf llvm-project/.git
- cmake -G Ninja -B build $(grep -v '^#' cmake-defines.txt) llvm-project/llvm
- date
- cmake --build build
- date
- df -h .
- cmake --install build --prefix install
- df -h .
- tar cvzf clang.tar.gz -C install/ .
- df -h .

test: off
