# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Clone, build, and package

on:
  push:
    branches:
      - main

jobs:
  clone_build_package:
    name: Clone, build, and package
    runs-on: macos-10.15
    steps:
      - name: check disk space
        run: df -h .
      - name: install Ninja
        run: brew install ninja
      - name: checkout build-llvm
        uses: actions/checkout@v2
      - name: checkout llvm-project
        uses: actions/checkout@v2
        with:
          repository: llvm/llvm-project
          path: llvm-project
          ref: 930c74f12d799c95e37a107bb692148b36493806
          fetch-depth: 1
      - name: configure
        run: cmake -G Ninja -B build $(grep -v '^#' cmake-defines.txt) llvm-project/llvm
      - name: check disk space
        run: df -h .
      - name: build
        run: cmake --build build
      - name: check disk space
        run: df -h .
      - name: create install
        run: cmake --install build --prefix install
      - name: check disk space
        run: df -h .
      - name: show disk usage
        run: du -h -d 1
