# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Create LLVM release

on:
  push:
    branches:
      - main

env:
  LLVM_REF: 930c74f12d799c95e37a107bb692148b36493806

jobs:
  release_from_source:
    strategy:
      fail-fast: false

      matrix:
        include:
          - os: ubuntu-18.04
            install_ninja_command: sudo apt install ninja-build
            cc: clang
            cxx: clang++
          - os: macos-10.15
            install_ninja_command: brew install ninja
            cc: clang
            cxx: clang++
          - os: windows-2019
            install_ninja_command: choco install ninja
            # llvm fails to build with mingw
            # maybe consider `choco install llvm` and just go ahead and build
            # with latest clang, to avoid difference across platforms?
            cc: cl
            cxx: cl

    defaults:
      run:
        shell: bash

    name: Build and package LLVM (${{matrix.os}})
    runs-on: ${{matrix.os}}
    steps:
      - name: check disk space
        run: df -h .

      - name: install Ninja
        run: ${{matrix.install_ninja_command}}

      - name: checkout build-llvm
        uses: actions/checkout@v2
      - name: checkout llvm-project
        uses: actions/checkout@v2
        with:
          repository: llvm/llvm-project
          path: llvm-project
          ref: ${{ env.LLVM_REF }}
          fetch-depth: 1

      - name: configure
        run: cmake -G Ninja -B build $(grep -v '^#' cmake-defines.txt) llvm-project/llvm
        env:
          CC: ${{matrix.cc}}
          CXX: ${{matrix.cxx}}

      - name: check disk space
        run: df -h .

      - name: build
        run: cmake --build build

      - name: check disk space
        run: df -h .

      - name: create install
        run: cmake --install build --prefix install

      - name: check disk space
        run: df -h .

      - name: package
        run: 7z a ../llvm.7z .
        working-directory: ./install

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          # runner.os is one of "Windows", "Linux", or "macOS"
          name: llvm-${{runner.os}}
          path: llvm.7z

      - name: check disk space
        run: df -h .
      - name: show disk usage
        run: du -h -d 1
